import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'nl';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    'hero.badge': 'Launching businesses online since 2020',
    'hero.title': 'Your Website.',
    'hero.title.highlight': 'Live in 48 Hours.',
    'hero.subtitle': 'Complete website design, development, hosting, and SEO optimization delivered in just two days. Stop losing customers to competitors with a website.',
    'hero.cta.primary': 'Get Your Quote in 5 Minutes',
    'hero.cta.secondary': 'Book Free 30-Min Strategy Call',
    'hero.stat.delivery': 'Delivery Time',
    'hero.stat.sites': 'Sites Launched',
    'hero.stat.satisfaction': 'Client Satisfaction',
    'hero.stat.support': 'Support Available',
    'hero.price': '€499',
    'hero.price.label': 'Starting from just',
    'hero.price.subtext': 'Complete professional website',
    'hero.price.includes1': 'Design & Development',
    'hero.price.includes2': 'Hosting & SEO',
    'hero.price.includes3': '48hr Delivery',
    'services.title': 'Everything You Need to Succeed Online',
    'services.subtitle': 'A complete solution for business owners who need a professional online presence, fast.',
    'services.design.title': 'Custom Website Design',
    'services.design.desc': 'Tailored, modern designs that reflect your brand identity and engage your target audience.',
    'services.design.feat1': 'Mobile-responsive',
    'services.design.feat2': 'Modern UI/UX',
    'services.design.feat3': 'Brand-aligned',
    'services.dev.title': '48-Hour Development',
    'services.dev.desc': 'Lightning-fast development without compromising quality. Your site goes live in just 2 days.',
    'services.dev.feat1': 'Rapid deployment',
    'services.dev.feat2': 'Quality assured',
    'services.dev.feat3': 'Production-ready',
    'services.seo.title': 'SEO Optimization',
    'services.seo.desc': 'Built-in SEO best practices to ensure your website ranks well and attracts organic traffic.',
    'services.seo.feat1': 'On-page SEO',
    'services.seo.feat2': 'Meta optimization',
    'services.seo.feat3': 'Performance tuned',
    'services.hosting.title': 'Reliable Hosting',
    'services.hosting.desc': 'Fast, secure hosting included. Your website stays online 24/7 with automatic backups.',
    'services.hosting.feat1': '99.9% uptime',
    'services.hosting.feat2': 'SSL certificate',
    'services.hosting.feat3': 'CDN enabled',
    'services.security.title': 'Security & Compliance',
    'services.security.desc': 'Enterprise-grade security measures to protect your website and customer data.',
    'services.security.feat1': 'SSL encryption',
    'services.security.feat2': 'Regular updates',
    'services.security.feat3': 'Data protection',
    'services.analytics.title': 'Analytics & Insights',
    'services.analytics.desc': 'Track your website performance with integrated analytics and conversion tracking.',
    'services.analytics.feat1': 'Traffic monitoring',
    'services.analytics.feat2': 'User behavior',
    'services.analytics.feat3': 'Conversion tracking',
    'trust.secure': 'Bank-Level Security',
    'trust.gdpr': 'GDPR Compliant',
    'trust.ssl': 'SSL Encrypted',
    'trust.uptime': '99.9% Uptime',
    'results.title': 'Real Results, Real Fast',
    'results.subtitle': 'Our clients see measurable business growth within weeks of launch',
    'results.metric1.value': '156%',
    'results.metric1.label': 'Average traffic increase',
    'results.metric2.value': '3.2x',
    'results.metric2.label': 'ROI in first 90 days',
    'results.metric3.value': '48hrs',
    'results.metric3.label': 'From start to launch',
    'results.metric4.value': '€127k',
    'results.metric4.label': 'Average revenue impact',
    'process.title': 'Our Proven 48-Hour Process',
    'process.subtitle': 'A streamlined workflow designed for speed without sacrificing quality.',
    'process.step1.title': 'Discovery Call OR Survey Completion',
    'process.step1.duration': '30 minutes',
    'process.step1.desc': 'We discuss your business goals, target audience, and website requirements. You share your vision, and we provide expert recommendations.',
    'process.step2.title': 'Design & Planning',
    'process.step2.duration': '6-8 hours',
    'process.step2.desc': 'Our designers create a custom layout tailored to your brand. We select the perfect color scheme, typography, and imagery to represent your business.',
    'process.step3.title': 'Development',
    'process.step3.duration': '24-30 hours',
    'process.step3.desc': 'We build your website with clean code, integrate all features, optimize for speed and SEO, and ensure mobile responsiveness across all devices.',
    'process.step4.title': 'Launch & Support',
    'process.step4.duration': '6-8 hours',
    'process.step4.desc': 'Final testing, your review and approval, deployment to production, and 30 days of complimentary support for any adjustments or questions.',
    'process.cta.title': 'From First Call to Live Website in 48 Hours',
    'process.cta.subtitle': 'While others take weeks or months, we deliver a complete, professional website in just two days.',
    'process.cta.button': 'Get Started Today',
    'process.cta.secondary': 'View Sample Timeline',
    'why.badge': 'WHY CHOOSE US',
    'why.title': 'Built for Success, Delivered with Speed',
    'why.subtitle': 'We combine cutting-edge technology with lightning-fast delivery to create websites that drive real business results.',
    'why.reason1.title': 'Lightning-Fast Results',
    'why.reason1.desc': 'Your website is live within 48 hours. No weeks of waiting, no endless meetings. Just results.',
    'why.reason1.badge': '48-hour guarantee',
    'why.reason2.title': 'Dutch Quality Standards',
    'why.reason2.desc': 'Built according to Dutch web standards with a focus on security, privacy, and GDPR compliance.',
    'why.reason2.badge': 'GDPR-proof',
    'why.reason3.title': 'Personal Approach',
    'why.reason3.desc': 'Direct contact with your developer. No call centers, no intermediaries. Just honest communication.',
    'why.reason3.badge': 'Direct contact',
    'why.reason4.title': 'Modern Technology',
    'why.reason4.desc': 'State-of-the-art development with the latest tools and frameworks. Your website stays relevant for years.',
    'why.reason4.badge': 'Future-proof',
    'why.reason5.title': 'Startup Mindset',
    'why.reason5.desc': 'We understand startups. Flexible, fast, and focused on growth. Your success is our success.',
    'why.reason5.badge': 'Startup-friendly',
    'why.reason6.title': 'Scalable & Flexible',
    'why.reason6.desc': 'Start small, grow big. Our websites grow with your business without complete restructuring.',
    'why.reason6.badge': 'Grow with you',
    'why.cta.title': 'Ready to Get Started?',
    'why.cta.subtitle': 'Fill out our quick form and receive a personalized quote within 24 hours.',
    'why.cta.button': 'Start Now',
    'why.cta.secondary': 'Request Quote',
    'faq.badge': 'Got Questions?',
    'faq.title': 'Frequently Asked Questions',
    'faq.subtitle': 'Everything you need to know about our 48-hour website service.',
    'faq.cta.title': 'Still have questions?',
    'faq.cta.subtitle': "We're here to help! Book a free consultation to discuss your specific needs.",
    'faq.cta.button': 'Talk to Our Team',
    'faq.q1': 'How can you build a professional website in just 48 hours?',
    'faq.a1': 'Our streamlined process and experienced team allow us to work efficiently without compromising quality. We use proven design templates that we customize to your brand, pre-built components for common features, and a dedicated workflow that eliminates back-and-forth delays. Plus, we focus exclusively on your project during those 48 hours.',
    'faq.q2': 'What happens if I need changes after the website is launched?',
    'faq.a2': 'Every website includes 30 days of free revisions and support after launch. After that, we offer affordable maintenance packages starting at $99/month, or you can request changes on an as-needed basis. Minor content updates are typically included, while significant redesigns would be quoted separately.',
    'faq.q3': 'Do I need to provide content and images?',
    'faq.a3': "While having your content ready speeds up the process, we can help! We offer professional copywriting services and have access to premium stock photo libraries. If you have specific brand photos or content, that's great. If not, we'll work with what you have and fill in the gaps to ensure your site looks professional.",
    'faq.q4': 'Is hosting and domain registration included?',
    'faq.a4': 'Yes! Your website includes one year of hosting on our high-performance servers with 99.9% uptime guarantee, SSL certificate for security, and automatic daily backups. Domain registration is separate and typically costs $12-15/year, which we can handle for you or you can purchase independently.',
    'faq.q5': 'Will my website work on mobile devices?',
    'faq.a5': 'Absolutely! Every website we build is fully responsive and optimized for all devices - phones, tablets, laptops, and desktops. We test on multiple screen sizes and browsers to ensure a perfect experience for all your visitors. Mobile optimization is a standard part of our process, not an extra.',
    'faq.q6': 'What about SEO? Will people find my website on Google?',
    'faq.a6': 'All our websites are built with SEO best practices from the ground up: fast loading speeds, clean code, proper meta tags, mobile optimization, and structured data. We also submit your site to Google and set up basic analytics. For ongoing SEO and content marketing, we offer optional monthly SEO packages.',
    'faq.q7': "Can I update the website myself after it's built?",
    'faq.a7': 'Yes! We can build your site on a user-friendly content management system (CMS) that allows you to make updates without technical knowledge. We provide training and documentation. Alternatively, we can handle all updates for you through our maintenance plans.',
    'faq.q8': 'What if I already have a website? Can you redesign it?',
    'faq.a8': "Definitely! We can redesign your existing website with our 48-hour service. We'll migrate your content, improve the design, enhance functionality, and ensure everything works perfectly. We can also keep your current domain and hosting if you prefer.",
    'faq.q9': 'Do you offer e-commerce functionality?',
    'faq.a9': "Yes, we can integrate e-commerce capabilities including product catalogs, shopping carts, and secure payment processing. Basic e-commerce sites (up to 50 products) fit within our standard 48-hour timeframe. Larger catalogs or complex requirements may need additional time, which we'll discuss upfront.",
    'faq.q10': 'What makes your service different from DIY website builders?',
    'faq.a10': 'While DIY builders are great for some, they require significant time investment and often result in cookie-cutter designs. We provide a completely custom, professional website without you having to learn new tools or spend weeks building it yourself. Plus, you get expert design advice, professional optimization, and ongoing support.',
    'faq.q11': 'Is there a money-back guarantee?',
    'faq.a11': "Yes! If we don't deliver your website within 48 hours (excluding revisions), you'll receive a full refund. Additionally, if you're not satisfied with the initial design, we'll work with you through unlimited revisions during the first 30 days until you love it.",
    'faq.q12': 'How do I get started?',
    'faq.a12': "Simply book a free 30-minute strategy call or fill out our quick quote form. We'll discuss your needs, show you examples, answer questions, and if you're ready to move forward, we can start immediately. Payment is 50% upfront and 50% upon delivery of your completed website.",
    'survey.title': 'Share Your Wishes',
    'survey.subtitle': "Let's build your perfect website together. This survey takes 10-15 minutes and helps us understand your exact needs.",
    'survey.select': 'Select an option...',
    'survey.other': 'Other',
    'survey.dont_know': "I don't know",
    'survey.pages_other_placeholder': 'Please specify other pages needed...',
    'survey.error': 'There was an error submitting your survey. Please try again.',
    'survey.submitting': 'Submitting...',
    'survey.submit': 'Submit Survey',
    'survey.success.title': 'Thank You!',
    'survey.success.message': "Your survey has been submitted successfully. We'll review your requirements and get back to you within 24 hours with a detailed proposal.",
    'survey.success.button': 'Back to Home',
    'survey.contact.title': 'Contact Information',
    'survey.contact.name': 'Your Name *',
    'survey.contact.email': 'Email Address *',
    'survey.contact.phone': 'Phone Number',
    'survey.contact.business': 'Business/Website Name',
    'survey.section1.title': 'Section 1: Content & Structure',
    'survey.section1.content_ready': 'Content Readiness',
    'survey.section1.content_ready_yes': 'Yes, all content is ready',
    'survey.section1.content_ready_partial': 'Partially ready',
    'survey.section1.content_ready_no': 'No, I need help creating content',
    'survey.section1.content_ready_unsure': 'Not sure what content I need',
    'survey.section1.content_support': 'Content Creation Support',
    'survey.section1.content_support_full': 'Yes, full copywriting service needed',
    'survey.section1.content_support_seo': 'Yes, just SEO optimization',
    'survey.section1.content_support_no': "No, I'll handle content myself",
    'survey.section1.content_support_consult': 'Need consultation to decide',
    'survey.section1.visual_assets': 'Visual Assets',
    'survey.section1.visual_assets_ready': 'Yes, I have all images ready',
    'survey.section1.visual_assets_some': 'I have some images but need more',
    'survey.section1.visual_assets_professional': 'No, I need professional photography/graphics',
    'survey.section1.visual_assets_stock': "I'll use stock photos",
    'survey.section1.pages': 'Main Pages/Sections Needed',
    'survey.section1.structure': 'Website Structure',
    'survey.section1.structure_one': 'One-page website',
    'survey.section1.structure_multi': 'Multi-page structure',
    'survey.section1.structure_unsure': 'Not sure - need recommendation',
    'survey.section2.title': 'Section 2: E-Commerce & Booking Features',
    'survey.section2.ecommerce': 'Do you want an online store (eCommerce)?',
    'survey.section2.ecommerce_yes': 'Yes, full eCommerce functionality needed',
    'survey.section2.ecommerce_maybe': 'Maybe in the future',
    'survey.section2.ecommerce_showcase': 'No, just showcase products/services',
    'survey.section2.ecommerce_na': 'Not applicable',
    'survey.section2.product_count': 'Product Count',
    'survey.section2.features': 'eCommerce Features',
    'survey.section2.features_wishlists': 'Wishlists',
    'survey.section2.features_reviews': 'Product Reviews',
    'survey.section2.features_discounts': 'Discount Codes',
    'survey.section2.booking': 'Booking System',
    'survey.section2.booking_yes': 'Yes, essential for my business',
    'survey.section2.booking_maybe': 'Maybe useful',
    'survey.section2.booking_no': 'No booking needed',
    'survey.section3.title': 'Section 3: Interactive Features',
    'survey.section3.communication': 'Communication Tools',
    'survey.section3.communication_contact': 'Contact form',
    'survey.section3.communication_quote': 'Quote form',
    'survey.section3.communication_chat': 'Live chat',
    'survey.section3.user_accounts': 'User Accounts',
    'survey.section3.accounts_customer': 'Yes, for customer accounts',
    'survey.section3.accounts_member': 'Yes, for member/partner access',
    'survey.section3.accounts_student': 'Yes, for student portal',
    'survey.section3.accounts_no': 'No user accounts needed',
    'survey.section3.blog': 'Blog',
    'survey.section3.blog_yes': 'Yes, I plan to blog regularly',
    'survey.section3.blog_maybe': 'Maybe occasionally',
    'survey.section3.blog_no': 'No blog needed',
    'survey.section3.multilanguage': 'Multi-language Support',
    'survey.section3.multilanguage_yes': 'Yes, need multiple languages',
    'survey.section3.multilanguage_maybe': 'Maybe in the future',
    'survey.section3.multilanguage_no': 'English only',
    'survey.section3.languages_placeholder': 'Which languages?',
    'survey.section4.title': 'Section 4: Integrations & Payments',
    'survey.section4.payments': 'Online Payments',
    'survey.section4.payments_yes': 'Yes, essential for my business',
    'survey.section4.payments_maybe': 'Maybe in the future',
    'survey.section4.payments_no': 'No payments needed',
    'survey.section4.payment_methods': 'Payment Methods',
    'survey.section4.method_cards': 'Credit/Debit cards',
    'survey.section4.existing_tools': 'Existing Tools to Integrate',
    'survey.section4.tools_skip': "I don't know - skip this section",
    'survey.section5.title': 'Section 5: SEO & Marketing',
    'survey.section5.seo': 'SEO Optimization',
    'survey.section5.seo_full': 'Yes, full SEO setup',
    'survey.section5.seo_basic': 'Yes, basic optimization only',
    'survey.section5.seo_self': "I'll handle SEO myself",
    'survey.section5.seo_later': 'Not important right now',
    'survey.section5.analytics': 'Analytics & Tracking',
    'survey.section5.analytics_all': 'All tracking tools',
    'survey.section5.analytics_ga': 'Just Google Analytics',
    'survey.section5.analytics_meta': 'Just Meta Pixel',
    'survey.section5.analytics_none': 'None needed',
    'survey.section6.title': 'Section 6: Maintenance & Management',
    'survey.section6.management': 'Website Management',
    'survey.section6.management_self': 'I want to manage it myself',
    'survey.section6.management_you': 'I want you to manage it',
    'survey.section6.management_shared': 'Shared management',
    'survey.section6.management_unsure': 'Not sure yet',
    'survey.section6.dashboard': 'Admin Dashboard',
    'survey.section6.dashboard_full': 'Yes, full editing capabilities',
    'survey.section6.dashboard_basic': 'Yes, basic content updates only',
    'survey.section6.dashboard_no': "No, I'll request changes through you",
    'survey.section7.title': 'Section 7: Technical Requirements',
    'survey.section7.domain': 'Domain Ownership',
    'survey.section7.domain_own': 'Yes, I own a domain',
    'survey.section7.domain_help': 'No, I need help choosing one',
    'survey.section7.domain_ideas': 'I have ideas but need guidance',
    'survey.section7.domain_name': 'Domain name',
    'survey.section7.responsive': 'Responsive Design',
    'survey.section7.responsive_all': 'Yes, optimize for all devices',
    'survey.section7.responsive_desktop': 'Desktop focus, mobile secondary',
    'survey.section7.responsive_mobile': 'Mobile-first design',
    'survey.timeline.title': 'Project Timeline & Budget',
    'survey.timeline.launch': 'Ideal Launch Date',
    'survey.timeline.asap': 'ASAP',
    'survey.timeline.2weeks': 'Within 2 weeks',
    'survey.timeline.1month': 'Within 1 month',
    'survey.timeline.2-3months': 'Within 2-3 months',
    'survey.timeline.flexible': 'Flexible',
    'survey.timeline.budget': 'Budget Range (Optional)',
    'survey.timeline.budget_under1k': 'Under €1,000',
    'survey.timeline.budget_1k3k': '€1,000-€3,000',
    'survey.timeline.budget_3k5k': '€3,000-€5,000',
    'survey.timeline.budget_5k10k': '€5,000-€10,000',
    'survey.timeline.budget_10k': '€10,000+',
    'survey.timeline.comments': 'Additional Comments or Special Requirements',
    'survey.timeline.comments_placeholder': 'Tell us anything else about your project...',
  },
  nl: {
    'hero.badge': 'Bedrijven online lanceren sinds 2020',
    'hero.title': 'Uw Website.',
    'hero.title.highlight': 'Live binnen 48 Uur.',
    'hero.subtitle': 'Complete website design, ontwikkeling, hosting en SEO optimalisatie geleverd in slechts twee dagen. Stop met het verliezen van klanten aan concurrenten met een website.',
    'hero.cta.primary': 'Krijg Uw Offerte in 5 Minuten',
    'hero.cta.secondary': 'Boek Gratis 30-Min Strategiegesprek',
    'hero.stat.delivery': 'Levertijd',
    'hero.stat.sites': 'Sites Gelanceerd',
    'hero.stat.satisfaction': 'Klanttevredenheid',
    'hero.stat.support': 'Support Beschikbaar',
    'hero.price': '€499',
    'hero.price.label': 'Vanaf slechts',
    'hero.price.subtext': 'Complete professionele website',
    'hero.price.includes1': 'Design & Ontwikkeling',
    'hero.price.includes2': 'Hosting & SEO',
    'hero.price.includes3': '48u Oplevering',
    'services.title': 'Alles Wat U Nodig Heeft Om Online Te Slagen',
    'services.subtitle': 'Een complete oplossing voor ondernemers die snel een professionele online aanwezigheid nodig hebben.',
    'services.design.title': 'Maatwerk Website Design',
    'services.design.desc': 'Op maat gemaakte, moderne designs die uw merkidentiteit weerspiegelen en uw doelgroep betrekken.',
    'services.design.feat1': 'Mobiel-responsive',
    'services.design.feat2': 'Modern UI/UX',
    'services.design.feat3': 'Merkgericht',
    'services.dev.title': '48-Uur Ontwikkeling',
    'services.dev.desc': 'Razendsnelle ontwikkeling zonder concessies aan kwaliteit. Uw site gaat live in slechts 2 dagen.',
    'services.dev.feat1': 'Snelle implementatie',
    'services.dev.feat2': 'Kwaliteit gegarandeerd',
    'services.dev.feat3': 'Productie-klaar',
    'services.seo.title': 'SEO Optimalisatie',
    'services.seo.desc': 'Ingebouwde SEO best practices om ervoor te zorgen dat uw website goed scoort en organisch verkeer aantrekt.',
    'services.seo.feat1': 'On-page SEO',
    'services.seo.feat2': 'Meta optimalisatie',
    'services.seo.feat3': 'Prestatie geoptimaliseerd',
    'services.hosting.title': 'Betrouwbare Hosting',
    'services.hosting.desc': 'Snelle, veilige hosting inbegrepen. Uw website blijft 24/7 online met automatische back-ups.',
    'services.hosting.feat1': '99.9% uptime',
    'services.hosting.feat2': 'SSL certificaat',
    'services.hosting.feat3': 'CDN ingeschakeld',
    'services.security.title': 'Beveiliging & Compliance',
    'services.security.desc': 'Beveiligingsmaatregelen op enterprise-niveau om uw website en klantgegevens te beschermen.',
    'services.security.feat1': 'SSL encryptie',
    'services.security.feat2': 'Regelmatige updates',
    'services.security.feat3': 'Gegevensbescherming',
    'services.analytics.title': 'Analytics & Inzichten',
    'services.analytics.desc': 'Volg de prestaties van uw website met geïntegreerde analytics en conversie tracking.',
    'services.analytics.feat1': 'Verkeer monitoring',
    'services.analytics.feat2': 'Gebruikersgedrag',
    'services.analytics.feat3': 'Conversie tracking',
    'trust.secure': 'Bank-Niveau Beveiliging',
    'trust.gdpr': 'AVG Conform',
    'trust.ssl': 'SSL Versleuteld',
    'trust.uptime': '99.9% Uptime',
    'results.title': 'Echte Resultaten, Supersnel',
    'results.subtitle': 'Onze klanten zien meetbare bedrijfsgroei binnen weken na lancering',
    'results.metric1.value': '156%',
    'results.metric1.label': 'Gemiddelde verkeersstijging',
    'results.metric2.value': '3.2x',
    'results.metric2.label': 'ROI in eerste 90 dagen',
    'results.metric3.value': '48uur',
    'results.metric3.label': 'Van start tot lancering',
    'results.metric4.value': '€127k',
    'results.metric4.label': 'Gemiddelde omzet impact',
    'process.title': 'Ons Bewezen 48-Uur Proces',
    'process.subtitle': 'Een gestroomlijnde workflow ontworpen voor snelheid zonder kwaliteit op te offeren.',
    'process.step1.title': 'Kennismakingsgesprek',
    'process.step1.duration': '30 minuten',
    'process.step1.desc': 'We bespreken uw bedrijfsdoelen, doelgroep en website-eisen. U deelt uw visie en wij geven deskundig advies.',
    'process.step2.title': 'Design & Planning',
    'process.step2.duration': '6-8 uur',
    'process.step2.desc': 'Onze designers creëren een op maat gemaakt ontwerp dat past bij uw merk. We selecteren het perfecte kleurenschema, typografie en beeldmateriaal voor uw bedrijf.',
    'process.step3.title': 'Ontwikkeling',
    'process.step3.duration': '24-30 uur',
    'process.step3.desc': 'We bouwen uw website met schone code, integreren alle functies, optimaliseren voor snelheid en SEO, en zorgen voor mobiele responsiviteit op alle apparaten.',
    'process.step4.title': 'Lancering & Support',
    'process.step4.duration': '6-8 uur',
    'process.step4.desc': 'Definitieve testen, uw beoordeling en goedkeuring, deployment naar productie, en 30 dagen gratis support voor aanpassingen of vragen.',
    'process.cta.title': 'Van Eerste Gesprek tot Live Website in 48 Uur',
    'process.cta.subtitle': 'Terwijl anderen weken of maanden nodig hebben, leveren wij een complete, professionele website in slechts twee dagen.',
    'process.cta.button': 'Start Vandaag Nog',
    'process.cta.secondary': 'Bekijk Voorbeeld Planning',
    'why.badge': 'WAAROM KIEZEN VOOR ONS',
    'why.title': 'Gebouwd voor Succes, Geleverd met Snelheid',
    'why.subtitle': 'We combineren geavanceerde technologie met razendsnelle levering om websites te creëren die echte bedrijfsresultaten opleveren.',
    'why.reason1.title': 'Razendsnel Resultaat',
    'why.reason1.desc': 'Uw website is binnen 48 uur live. Geen weken wachten, geen eindeloze vergaderingen. Gewoon resultaat.',
    'why.reason1.badge': '48 uur garantie',
    'why.reason2.title': 'Nederlandse Kwaliteit',
    'why.reason2.desc': 'Gebouwd volgens Nederlandse webstandards met focus op beveiliging, privacy en GDPR-compliance.',
    'why.reason2.badge': 'AVG-proof',
    'why.reason3.title': 'Persoonlijke Aanpak',
    'why.reason3.desc': 'Direct contact met uw ontwikkelaar. Geen callcenters, geen tussenpersonen. Gewoon eerlijke communicatie.',
    'why.reason3.badge': 'Direct contact',
    'why.reason4.title': 'Moderne Technologie',
    'why.reason4.desc': 'State-of-the-art development met de nieuwste tools en frameworks. Uw website blijft jaren actueel.',
    'why.reason4.badge': 'Toekomstbestendig',
    'why.reason5.title': 'Startup Mindset',
    'why.reason5.desc': 'Wij begrijpen startups. Flexibel, snel en gefocust op groei. Uw succes is ons succes.',
    'why.reason5.badge': 'Startup-vriendelijk',
    'why.reason6.title': 'Schaalbaar & Flexibel',
    'why.reason6.desc': 'Begin klein, groei groot. Onze websites groeien mee met uw bedrijf zonder complete herstructurering.',
    'why.reason6.badge': 'Groei mee',
    'why.cta.title': 'Klaar om te Starten?',
    'why.cta.subtitle': 'Vul ons snelle formulier in en ontvang binnen 24 uur een persoonlijke offerte op maat.',
    'why.cta.button': 'Start Nu Direct',
    'why.cta.secondary': 'Vraag Offerte Aan',
    'faq.badge': 'Vragen?',
    'faq.title': 'Veelgestelde Vragen',
    'faq.subtitle': 'Alles wat u moet weten over onze 48-uur website service.',
    'faq.cta.title': 'Nog vragen?',
    'faq.cta.subtitle': 'We helpen u graag! Boek een gratis consult om uw specifieke behoeften te bespreken.',
    'faq.cta.button': 'Neem Contact Op',
    'faq.q1': 'Hoe kunnen jullie een professionele website bouwen in slechts 48 uur?',
    'faq.a1': 'Ons gestroomlijnde proces en ervaren team stellen ons in staat om efficiënt te werken zonder concessies te doen aan kwaliteit. We gebruiken bewezen designsjablonen die we aanpassen aan uw merk, voorgebouwde componenten voor veelvoorkomende functies, en een toegewijde workflow die heen-en-weer vertragingen elimineert. Bovendien richten we ons exclusief op uw project tijdens die 48 uur.',
    'faq.q2': 'Wat gebeurt er als ik wijzigingen nodig heb nadat de website is gelanceerd?',
    'faq.a2': 'Elke website bevat 30 dagen gratis revisies en ondersteuning na lancering. Daarna bieden we betaalbare onderhoudspakketten aan vanaf €99/maand, of u kunt wijzigingen aanvragen op basis van behoefte. Kleine contentwijzigingen zijn meestal inbegrepen, terwijl significante herontwerpen afzonderlijk worden geoffreerd.',
    'faq.q3': 'Moet ik zelf content en afbeeldingen aanleveren?',
    'faq.a3': 'Hoewel het klaar hebben van uw content het proces versnelt, kunnen we helpen! We bieden professionele copywriting diensten aan en hebben toegang tot premium stockfotobibliotheken. Als u specifieke merkfoto\'s of content heeft, is dat geweldig. Zo niet, dan werken we met wat u heeft en vullen we de hiaten om ervoor te zorgen dat uw site er professioneel uitziet.',
    'faq.q4': 'Is hosting en domeinregistratie inbegrepen?',
    'faq.a4': 'Ja! Uw website bevat één jaar hosting op onze krachtige servers met 99,9% uptime garantie, SSL-certificaat voor beveiliging en automatische dagelijkse back-ups. Domeinregistratie is afzonderlijk en kost meestal €12-15/jaar, wat we voor u kunnen regelen of u kunt het zelfstandig aanschaffen.',
    'faq.q5': 'Werkt mijn website op mobiele apparaten?',
    'faq.a5': 'Absoluut! Elke website die we bouwen is volledig responsive en geoptimaliseerd voor alle apparaten - telefoons, tablets, laptops en desktops. We testen op meerdere schermformaten en browsers om een perfecte ervaring voor al uw bezoekers te garanderen. Mobiele optimalisatie is een standaard onderdeel van ons proces, geen extra.',
    'faq.q6': 'Hoe zit het met SEO? Zullen mensen mijn website vinden op Google?',
    'faq.a6': 'Al onze websites zijn vanaf de grond gebouwd met SEO best practices: snelle laadsnelheden, schone code, juiste meta tags, mobiele optimalisatie en gestructureerde data. We dienen ook uw site in bij Google en stellen basis analytics in. Voor doorlopende SEO en contentmarketing bieden we optionele maandelijkse SEO-pakketten.',
    'faq.q7': 'Kan ik de website zelf bijwerken nadat deze is gebouwd?',
    'faq.a7': 'Ja! We kunnen uw site bouwen op een gebruiksvriendelijk content management systeem (CMS) waarmee u updates kunt maken zonder technische kennis. We bieden training en documentatie. Als alternatief kunnen we alle updates voor u afhandelen via onze onderhoudsplannen.',
    'faq.q8': 'Wat als ik al een website heb? Kunnen jullie deze herontwerpen?',
    'faq.a8': 'Zeker! We kunnen uw bestaande website herontwerpen met onze 48-uur service. We migreren uw content, verbeteren het ontwerp, verbeteren de functionaliteit en zorgen ervoor dat alles perfect werkt. We kunnen ook uw huidige domein en hosting behouden als u dat wenst.',
    'faq.q9': 'Bieden jullie e-commerce functionaliteit?',
    'faq.a9': 'Ja, we kunnen e-commerce mogelijkheden integreren inclusief productcatalogi, winkelwagentjes en veilige betalingsverwerking. Basis e-commerce sites (tot 50 producten) passen binnen ons standaard 48-uur tijdsbestek. Grotere catalogi of complexe vereisten kunnen extra tijd nodig hebben, wat we vooraf bespreken.',
    'faq.q10': 'Wat maakt jullie service anders dan DIY website builders?',
    'faq.a10': 'Hoewel DIY builders geweldig zijn voor sommigen, vereisen ze een aanzienlijke tijdsinvestering en resulteren vaak in standaard ontwerpen. We bieden een volledig op maat gemaakte, professionele website zonder dat u nieuwe tools hoeft te leren of weken moet besteden aan het zelf bouwen. Bovendien krijgt u deskundig ontwerpadvies, professionele optimalisatie en doorlopende ondersteuning.',
    'faq.q11': 'Is er een geld-terug-garantie?',
    'faq.a11': 'Ja! Als we uw website niet binnen 48 uur opleveren (exclusief revisies), ontvangt u een volledige terugbetaling. Bovendien, als u niet tevreden bent met het initiële ontwerp, werken we met u door onbeperkte revisies gedurende de eerste 30 dagen totdat u het geweldig vindt.',
    'faq.q12': 'Hoe kan ik beginnen?',
    'faq.a12': 'Boek simpelweg een gratis 30-minuten strategiegesprek of vul ons snelle offerteformulier in. We bespreken uw behoeften, tonen u voorbeelden, beantwoorden vragen, en als u klaar bent om verder te gaan, kunnen we onmiddellijk beginnen. Betaling is 50% vooraf en 50% bij oplevering van uw voltooide website.',
    'survey.title': 'Deel Uw Wensen',
    'survey.subtitle': 'Laten we samen uw perfecte website bouwen. Deze vragenlijst duurt 10-15 minuten en helpt ons uw exacte behoeften te begrijpen.',
    'survey.select': 'Selecteer een optie...',
    'survey.other': 'Anders',
    'survey.dont_know': 'Ik weet het niet',
    'survey.pages_other_placeholder': 'Specificeer andere benodigde pagina\'s...',
    'survey.error': 'Er is een fout opgetreden bij het indienen van uw enquête. Probeer het opnieuw.',
    'survey.submitting': 'Bezig met verzenden...',
    'survey.submit': 'Enquête Indienen',
    'survey.success.title': 'Bedankt!',
    'survey.success.message': 'Uw enquête is succesvol ingediend. We zullen uw vereisten bekijken en binnen 24 uur contact met u opnemen met een gedetailleerd voorstel.',
    'survey.success.button': 'Terug naar Home',
    'survey.contact.title': 'Contactinformatie',
    'survey.contact.name': 'Uw Naam *',
    'survey.contact.email': 'E-mailadres *',
    'survey.contact.phone': 'Telefoonnummer',
    'survey.contact.business': 'Bedrijfs-/Websitenaam',
    'survey.section1.title': 'Sectie 1: Inhoud & Structuur',
    'survey.section1.content_ready': 'Content Gereedheid',
    'survey.section1.content_ready_yes': 'Ja, alle content is klaar',
    'survey.section1.content_ready_partial': 'Gedeeltelijk klaar',
    'survey.section1.content_ready_no': 'Nee, ik heb hulp nodig bij het creëren van content',
    'survey.section1.content_ready_unsure': 'Niet zeker welke content ik nodig heb',
    'survey.section1.content_support': 'Content Creatie Ondersteuning',
    'survey.section1.content_support_full': 'Ja, volledige copywriting service nodig',
    'survey.section1.content_support_seo': 'Ja, alleen SEO optimalisatie',
    'survey.section1.content_support_no': 'Nee, ik handel de content zelf af',
    'survey.section1.content_support_consult': 'Heb consultatie nodig om te beslissen',
    'survey.section1.visual_assets': 'Visuele Middelen',
    'survey.section1.visual_assets_ready': 'Ja, ik heb alle afbeeldingen klaar',
    'survey.section1.visual_assets_some': 'Ik heb enkele afbeeldingen maar heb meer nodig',
    'survey.section1.visual_assets_professional': 'Nee, ik heb professionele fotografie/graphics nodig',
    'survey.section1.visual_assets_stock': 'Ik gebruik stockfoto\'s',
    'survey.section1.pages': 'Belangrijkste Pagina\'s/Secties Nodig',
    'survey.section1.structure': 'Website Structuur',
    'survey.section1.structure_one': 'Eén-pagina website',
    'survey.section1.structure_multi': 'Multi-pagina structuur',
    'survey.section1.structure_unsure': 'Niet zeker - heb aanbeveling nodig',
    'survey.section2.title': 'Sectie 2: E-Commerce & Boekingsfuncties',
    'survey.section2.ecommerce': 'Wilt u een online winkel (eCommerce)?',
    'survey.section2.ecommerce_yes': 'Ja, volledige eCommerce functionaliteit nodig',
    'survey.section2.ecommerce_maybe': 'Misschien in de toekomst',
    'survey.section2.ecommerce_showcase': 'Nee, alleen producten/diensten tonen',
    'survey.section2.ecommerce_na': 'Niet van toepassing',
    'survey.section2.product_count': 'Aantal Producten',
    'survey.section2.features': 'eCommerce Functies',
    'survey.section2.features_wishlists': 'Verlanglijsten',
    'survey.section2.features_reviews': 'Productbeoordelingen',
    'survey.section2.features_discounts': 'Kortingscodes',
    'survey.section2.booking': 'Boekingssysteem',
    'survey.section2.booking_yes': 'Ja, essentieel voor mijn bedrijf',
    'survey.section2.booking_maybe': 'Misschien nuttig',
    'survey.section2.booking_no': 'Geen boeking nodig',
    'survey.section3.title': 'Sectie 3: Interactieve Functies',
    'survey.section3.communication': 'Communicatiemiddelen',
    'survey.section3.communication_contact': 'Contactformulier',
    'survey.section3.communication_quote': 'Offerteformulier',
    'survey.section3.communication_chat': 'Live chat',
    'survey.section3.user_accounts': 'Gebruikersaccounts',
    'survey.section3.accounts_customer': 'Ja, voor klantaccounts',
    'survey.section3.accounts_member': 'Ja, voor lid/partner toegang',
    'survey.section3.accounts_student': 'Ja, voor studentenportaal',
    'survey.section3.accounts_no': 'Geen gebruikersaccounts nodig',
    'survey.section3.blog': 'Blog',
    'survey.section3.blog_yes': 'Ja, ik ben van plan regelmatig te bloggen',
    'survey.section3.blog_maybe': 'Misschien af en toe',
    'survey.section3.blog_no': 'Geen blog nodig',
    'survey.section3.multilanguage': 'Meertalige Ondersteuning',
    'survey.section3.multilanguage_yes': 'Ja, meerdere talen nodig',
    'survey.section3.multilanguage_maybe': 'Misschien in de toekomst',
    'survey.section3.multilanguage_no': 'Alleen Engels',
    'survey.section3.languages_placeholder': 'Welke talen?',
    'survey.section4.title': 'Sectie 4: Integraties & Betalingen',
    'survey.section4.payments': 'Online Betalingen',
    'survey.section4.payments_yes': 'Ja, essentieel voor mijn bedrijf',
    'survey.section4.payments_maybe': 'Misschien in de toekomst',
    'survey.section4.payments_no': 'Geen betalingen nodig',
    'survey.section4.payment_methods': 'Betaalmethoden',
    'survey.section4.method_cards': 'Credit/Debit kaarten',
    'survey.section4.existing_tools': 'Bestaande Tools om te Integreren',
    'survey.section4.tools_skip': 'Ik weet het niet - sla deze sectie over',
    'survey.section5.title': 'Sectie 5: SEO & Marketing',
    'survey.section5.seo': 'SEO Optimalisatie',
    'survey.section5.seo_full': 'Ja, volledige SEO setup',
    'survey.section5.seo_basic': 'Ja, alleen basis optimalisatie',
    'survey.section5.seo_self': 'Ik handel SEO zelf af',
    'survey.section5.seo_later': 'Nu niet belangrijk',
    'survey.section5.analytics': 'Analytics & Tracking',
    'survey.section5.analytics_all': 'Alle tracking tools',
    'survey.section5.analytics_ga': 'Alleen Google Analytics',
    'survey.section5.analytics_meta': 'Alleen Meta Pixel',
    'survey.section5.analytics_none': 'Geen nodig',
    'survey.section6.title': 'Sectie 6: Onderhoud & Beheer',
    'survey.section6.management': 'Website Beheer',
    'survey.section6.management_self': 'Ik wil het zelf beheren',
    'survey.section6.management_you': 'Ik wil dat u het beheert',
    'survey.section6.management_shared': 'Gedeeld beheer',
    'survey.section6.management_unsure': 'Nog niet zeker',
    'survey.section6.dashboard': 'Admin Dashboard',
    'survey.section6.dashboard_full': 'Ja, volledige bewerkingsmogelijkheden',
    'survey.section6.dashboard_basic': 'Ja, alleen basis content updates',
    'survey.section6.dashboard_no': 'Nee, ik vraag wijzigingen aan via u',
    'survey.section7.title': 'Sectie 7: Technische Vereisten',
    'survey.section7.domain': 'Domein Eigendom',
    'survey.section7.domain_own': 'Ja, ik bezit een domein',
    'survey.section7.domain_help': 'Nee, ik heb hulp nodig bij het kiezen',
    'survey.section7.domain_ideas': 'Ik heb ideeën maar heb begeleiding nodig',
    'survey.section7.domain_name': 'Domeinnaam',
    'survey.section7.responsive': 'Responsief Ontwerp',
    'survey.section7.responsive_all': 'Ja, optimaliseer voor alle apparaten',
    'survey.section7.responsive_desktop': 'Desktop focus, mobiel secundair',
    'survey.section7.responsive_mobile': 'Mobiel-eerst ontwerp',
    'survey.timeline.title': 'Project Tijdlijn & Budget',
    'survey.timeline.launch': 'Ideale Lanceringsdatum',
    'survey.timeline.asap': 'Zo snel mogelijk',
    'survey.timeline.2weeks': 'Binnen 2 weken',
    'survey.timeline.1month': 'Binnen 1 maand',
    'survey.timeline.2-3months': 'Binnen 2-3 maanden',
    'survey.timeline.flexible': 'Flexibel',
    'survey.timeline.budget': 'Budgetbereik (Optioneel)',
    'survey.timeline.budget_under1k': 'Onder €1.000',
    'survey.timeline.budget_1k3k': '€1.000-€3.000',
    'survey.timeline.budget_3k5k': '€3.000-€5.000',
    'survey.timeline.budget_5k10k': '€5.000-€10.000',
    'survey.timeline.budget_10k': '€10.000+',
    'survey.timeline.comments': 'Aanvullende Opmerkingen of Speciale Vereisten',
    'survey.timeline.comments_placeholder': 'Vertel ons iets anders over uw project...',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
