import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'nl';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    'hero.badge': 'Launching businesses online since 2020',
    'hero.title': 'Your Website.',
    'hero.title.highlight': 'Live in 48 Hours.',
    'hero.subtitle': 'Complete website design, development, hosting, and SEO optimization delivered in just two days. Stop losing customers to competitors with a website.',
    'hero.cta.primary': 'Book Free 30-Min Strategy Call',
    'hero.cta.secondary': 'Get Your Quote in 5 Minutes',
    'hero.stat.delivery': 'Delivery Time',
    'hero.stat.sites': 'Sites Launched',
    'hero.stat.satisfaction': 'Client Satisfaction',
    'hero.stat.support': 'Support Available',
    'hero.price': '€699',
    'hero.price.label': 'Starting from',
    'hero.price.subtext': 'Complete professional website',
    'services.title': 'Everything You Need to Succeed Online',
    'services.subtitle': 'A complete solution for business owners who need a professional online presence, fast.',
    'services.design.title': 'Custom Website Design',
    'services.design.desc': 'Tailored, modern designs that reflect your brand identity and engage your target audience.',
    'services.design.feat1': 'Mobile-responsive',
    'services.design.feat2': 'Modern UI/UX',
    'services.design.feat3': 'Brand-aligned',
    'services.dev.title': '48-Hour Development',
    'services.dev.desc': 'Lightning-fast development without compromising quality. Your site goes live in just 2 days.',
    'services.dev.feat1': 'Rapid deployment',
    'services.dev.feat2': 'Quality assured',
    'services.dev.feat3': 'Production-ready',
    'services.seo.title': 'SEO Optimization',
    'services.seo.desc': 'Built-in SEO best practices to ensure your website ranks well and attracts organic traffic.',
    'services.seo.feat1': 'On-page SEO',
    'services.seo.feat2': 'Meta optimization',
    'services.seo.feat3': 'Performance tuned',
    'services.hosting.title': 'Reliable Hosting',
    'services.hosting.desc': 'Fast, secure hosting included. Your website stays online 24/7 with automatic backups.',
    'services.hosting.feat1': '99.9% uptime',
    'services.hosting.feat2': 'SSL certificate',
    'services.hosting.feat3': 'CDN enabled',
    'services.security.title': 'Security & Compliance',
    'services.security.desc': 'Enterprise-grade security measures to protect your website and customer data.',
    'services.security.feat1': 'SSL encryption',
    'services.security.feat2': 'Regular updates',
    'services.security.feat3': 'Data protection',
    'services.analytics.title': 'Analytics & Insights',
    'services.analytics.desc': 'Track your website performance with integrated analytics and conversion tracking.',
    'services.analytics.feat1': 'Traffic monitoring',
    'services.analytics.feat2': 'User behavior',
    'services.analytics.feat3': 'Conversion tracking',
    'trust.secure': 'Bank-Level Security',
    'trust.gdpr': 'GDPR Compliant',
    'trust.ssl': 'SSL Encrypted',
    'trust.uptime': '99.9% Uptime',
    'results.title': 'Real Results, Real Fast',
    'results.subtitle': 'Our clients see measurable business growth within weeks of launch',
    'results.metric1.value': '156%',
    'results.metric1.label': 'Average traffic increase',
    'results.metric2.value': '3.2x',
    'results.metric2.label': 'ROI in first 90 days',
    'results.metric3.value': '48hrs',
    'results.metric3.label': 'From start to launch',
    'results.metric4.value': '€127k',
    'results.metric4.label': 'Average revenue impact',
    'process.title': 'Our Proven 48-Hour Process',
    'process.subtitle': 'A streamlined workflow designed for speed without sacrificing quality.',
    'process.step1.title': 'Discovery Call',
    'process.step1.duration': '30 minutes',
    'process.step1.desc': 'We discuss your business goals, target audience, and website requirements. You share your vision, and we provide expert recommendations.',
    'process.step2.title': 'Design & Planning',
    'process.step2.duration': '6-8 hours',
    'process.step2.desc': 'Our designers create a custom layout tailored to your brand. We select the perfect color scheme, typography, and imagery to represent your business.',
    'process.step3.title': 'Development',
    'process.step3.duration': '24-30 hours',
    'process.step3.desc': 'We build your website with clean code, integrate all features, optimize for speed and SEO, and ensure mobile responsiveness across all devices.',
    'process.step4.title': 'Launch & Support',
    'process.step4.duration': '6-8 hours',
    'process.step4.desc': 'Final testing, your review and approval, deployment to production, and 30 days of complimentary support for any adjustments or questions.',
    'process.cta.title': 'From First Call to Live Website in 48 Hours',
    'process.cta.subtitle': 'While others take weeks or months, we deliver a complete, professional website in just two days.',
    'process.cta.button': 'Get Started Today',
    'process.cta.secondary': 'View Sample Timeline',
    'why.badge': 'WHY CHOOSE US',
    'why.title': 'Built for Success, Delivered with Speed',
    'why.subtitle': 'We combine cutting-edge technology with lightning-fast delivery to create websites that drive real business results.',
    'why.reason1.title': 'Lightning-Fast Results',
    'why.reason1.desc': 'Your website is live within 48 hours. No weeks of waiting, no endless meetings. Just results.',
    'why.reason1.badge': '48-hour guarantee',
    'why.reason2.title': 'Dutch Quality Standards',
    'why.reason2.desc': 'Built according to Dutch web standards with a focus on security, privacy, and GDPR compliance.',
    'why.reason2.badge': 'GDPR-proof',
    'why.reason3.title': 'Personal Approach',
    'why.reason3.desc': 'Direct contact with your developer. No call centers, no intermediaries. Just honest communication.',
    'why.reason3.badge': 'Direct contact',
    'why.reason4.title': 'Modern Technology',
    'why.reason4.desc': 'State-of-the-art development with the latest tools and frameworks. Your website stays relevant for years.',
    'why.reason4.badge': 'Future-proof',
    'why.reason5.title': 'Startup Mindset',
    'why.reason5.desc': 'We understand startups. Flexible, fast, and focused on growth. Your success is our success.',
    'why.reason5.badge': 'Startup-friendly',
    'why.reason6.title': 'Scalable & Flexible',
    'why.reason6.desc': 'Start small, grow big. Our websites grow with your business without complete restructuring.',
    'why.reason6.badge': 'Grow with you',
    'why.cta.title': 'Ready to Get Started?',
    'why.cta.subtitle': 'Fill out our quick form and receive a personalized quote within 24 hours.',
    'why.cta.button': 'Start Now',
    'why.cta.secondary': 'Request Quote',
    'faq.badge': 'Got Questions?',
    'faq.title': 'Frequently Asked Questions',
    'faq.subtitle': 'Everything you need to know about our 48-hour website service.',
    'faq.cta.title': 'Still have questions?',
    'faq.cta.subtitle': "We're here to help! Book a free consultation to discuss your specific needs.",
    'faq.cta.button': 'Talk to Our Team',
  },
  nl: {
    'hero.badge': 'Bedrijven online lanceren sinds 2020',
    'hero.title': 'Uw Website.',
    'hero.title.highlight': 'Live binnen 48 Uur.',
    'hero.subtitle': 'Complete website design, ontwikkeling, hosting en SEO optimalisatie geleverd in slechts twee dagen. Stop met het verliezen van klanten aan concurrenten met een website.',
    'hero.cta.primary': 'Boek Gratis 30-Min Strategiegesprek',
    'hero.cta.secondary': 'Krijg Uw Offerte in 5 Minuten',
    'hero.stat.delivery': 'Levertijd',
    'hero.stat.sites': 'Sites Gelanceerd',
    'hero.stat.satisfaction': 'Klanttevredenheid',
    'hero.stat.support': 'Support Beschikbaar',
    'hero.price': '€699',
    'hero.price.label': 'Vanaf',
    'hero.price.subtext': 'Complete professionele website',
    'services.title': 'Alles Wat U Nodig Heeft Om Online Te Slagen',
    'services.subtitle': 'Een complete oplossing voor ondernemers die snel een professionele online aanwezigheid nodig hebben.',
    'services.design.title': 'Maatwerk Website Design',
    'services.design.desc': 'Op maat gemaakte, moderne designs die uw merkidentiteit weerspiegelen en uw doelgroep betrekken.',
    'services.design.feat1': 'Mobiel-responsive',
    'services.design.feat2': 'Modern UI/UX',
    'services.design.feat3': 'Merkgericht',
    'services.dev.title': '48-Uur Ontwikkeling',
    'services.dev.desc': 'Razendsnelle ontwikkeling zonder concessies aan kwaliteit. Uw site gaat live in slechts 2 dagen.',
    'services.dev.feat1': 'Snelle implementatie',
    'services.dev.feat2': 'Kwaliteit gegarandeerd',
    'services.dev.feat3': 'Productie-klaar',
    'services.seo.title': 'SEO Optimalisatie',
    'services.seo.desc': 'Ingebouwde SEO best practices om ervoor te zorgen dat uw website goed scoort en organisch verkeer aantrekt.',
    'services.seo.feat1': 'On-page SEO',
    'services.seo.feat2': 'Meta optimalisatie',
    'services.seo.feat3': 'Prestatie geoptimaliseerd',
    'services.hosting.title': 'Betrouwbare Hosting',
    'services.hosting.desc': 'Snelle, veilige hosting inbegrepen. Uw website blijft 24/7 online met automatische back-ups.',
    'services.hosting.feat1': '99.9% uptime',
    'services.hosting.feat2': 'SSL certificaat',
    'services.hosting.feat3': 'CDN ingeschakeld',
    'services.security.title': 'Beveiliging & Compliance',
    'services.security.desc': 'Beveiligingsmaatregelen op enterprise-niveau om uw website en klantgegevens te beschermen.',
    'services.security.feat1': 'SSL encryptie',
    'services.security.feat2': 'Regelmatige updates',
    'services.security.feat3': 'Gegevensbescherming',
    'services.analytics.title': 'Analytics & Inzichten',
    'services.analytics.desc': 'Volg de prestaties van uw website met geïntegreerde analytics en conversie tracking.',
    'services.analytics.feat1': 'Verkeer monitoring',
    'services.analytics.feat2': 'Gebruikersgedrag',
    'services.analytics.feat3': 'Conversie tracking',
    'trust.secure': 'Bank-Niveau Beveiliging',
    'trust.gdpr': 'AVG Conform',
    'trust.ssl': 'SSL Versleuteld',
    'trust.uptime': '99.9% Uptime',
    'results.title': 'Echte Resultaten, Supersnel',
    'results.subtitle': 'Onze klanten zien meetbare bedrijfsgroei binnen weken na lancering',
    'results.metric1.value': '156%',
    'results.metric1.label': 'Gemiddelde verkeersstijging',
    'results.metric2.value': '3.2x',
    'results.metric2.label': 'ROI in eerste 90 dagen',
    'results.metric3.value': '48uur',
    'results.metric3.label': 'Van start tot lancering',
    'results.metric4.value': '€127k',
    'results.metric4.label': 'Gemiddelde omzet impact',
    'process.title': 'Ons Bewezen 48-Uur Proces',
    'process.subtitle': 'Een gestroomlijnde workflow ontworpen voor snelheid zonder kwaliteit op te offeren.',
    'process.step1.title': 'Kennismakingsgesprek',
    'process.step1.duration': '30 minuten',
    'process.step1.desc': 'We bespreken uw bedrijfsdoelen, doelgroep en website-eisen. U deelt uw visie en wij geven deskundig advies.',
    'process.step2.title': 'Design & Planning',
    'process.step2.duration': '6-8 uur',
    'process.step2.desc': 'Onze designers creëren een op maat gemaakt ontwerp dat past bij uw merk. We selecteren het perfecte kleurenschema, typografie en beeldmateriaal voor uw bedrijf.',
    'process.step3.title': 'Ontwikkeling',
    'process.step3.duration': '24-30 uur',
    'process.step3.desc': 'We bouwen uw website met schone code, integreren alle functies, optimaliseren voor snelheid en SEO, en zorgen voor mobiele responsiviteit op alle apparaten.',
    'process.step4.title': 'Lancering & Support',
    'process.step4.duration': '6-8 uur',
    'process.step4.desc': 'Definitieve testen, uw beoordeling en goedkeuring, deployment naar productie, en 30 dagen gratis support voor aanpassingen of vragen.',
    'process.cta.title': 'Van Eerste Gesprek tot Live Website in 48 Uur',
    'process.cta.subtitle': 'Terwijl anderen weken of maanden nodig hebben, leveren wij een complete, professionele website in slechts twee dagen.',
    'process.cta.button': 'Start Vandaag Nog',
    'process.cta.secondary': 'Bekijk Voorbeeld Planning',
    'why.badge': 'WAAROM KIEZEN VOOR ONS',
    'why.title': 'Gebouwd voor Succes, Geleverd met Snelheid',
    'why.subtitle': 'We combineren geavanceerde technologie met razendsnelle levering om websites te creëren die echte bedrijfsresultaten opleveren.',
    'why.reason1.title': 'Razendsnel Resultaat',
    'why.reason1.desc': 'Uw website is binnen 48 uur live. Geen weken wachten, geen eindeloze vergaderingen. Gewoon resultaat.',
    'why.reason1.badge': '48 uur garantie',
    'why.reason2.title': 'Nederlandse Kwaliteit',
    'why.reason2.desc': 'Gebouwd volgens Nederlandse webstandards met focus op beveiliging, privacy en GDPR-compliance.',
    'why.reason2.badge': 'AVG-proof',
    'why.reason3.title': 'Persoonlijke Aanpak',
    'why.reason3.desc': 'Direct contact met uw ontwikkelaar. Geen callcenters, geen tussenpersonen. Gewoon eerlijke communicatie.',
    'why.reason3.badge': 'Direct contact',
    'why.reason4.title': 'Moderne Technologie',
    'why.reason4.desc': 'State-of-the-art development met de nieuwste tools en frameworks. Uw website blijft jaren actueel.',
    'why.reason4.badge': 'Toekomstbestendig',
    'why.reason5.title': 'Startup Mindset',
    'why.reason5.desc': 'Wij begrijpen startups. Flexibel, snel en gefocust op groei. Uw succes is ons succes.',
    'why.reason5.badge': 'Startup-vriendelijk',
    'why.reason6.title': 'Schaalbaar & Flexibel',
    'why.reason6.desc': 'Begin klein, groei groot. Onze websites groeien mee met uw bedrijf zonder complete herstructurering.',
    'why.reason6.badge': 'Groei mee',
    'why.cta.title': 'Klaar om te Starten?',
    'why.cta.subtitle': 'Vul ons snelle formulier in en ontvang binnen 24 uur een persoonlijke offerte op maat.',
    'why.cta.button': 'Start Nu Direct',
    'why.cta.secondary': 'Vraag Offerte Aan',
    'faq.badge': 'Vragen?',
    'faq.title': 'Veelgestelde Vragen',
    'faq.subtitle': 'Alles wat u moet weten over onze 48-uur website service.',
    'faq.cta.title': 'Nog vragen?',
    'faq.cta.subtitle': 'We helpen u graag! Boek een gratis consult om uw specifieke behoeften te bespreken.',
    'faq.cta.button': 'Neem Contact Op',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
